export const SHOW_ALL = 'SHOW_ALL'
export const MEMORIZED = 'MEMORIZED'
export const NEED_PRACTICE = 'NEED_PRACTICE'

export const ACTION_TYPES = {
  FILTER_SHOW_ALL: 'FILTER_SHOW_ALL',
  FILTER_MEMORIZED: 'FILTER_MEMORIZED',
  FILTER_NEED_PRACTICE: 'FILTER_NEED_PRACTICE',
  TOGGLE_MEMORIZED_ITEM: 'TOGGLE_MEMORIZED_ITEM',
  SHOW_ITEM: 'SHOW_ITEM',
  SHOW_ADDFORM: 'SHOW_ADDFORM',
  ADD_WORD: 'ADD_WORD'
}
